In [182]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from funpymodeling import status, profiling_num, freq_tbl
from ydata_profiling import ProfileReport

In [183]:
data=pd.read_csv('encuesta-anual-hogares-2019.csv',sep=',')
pd.set_option('display.max_columns', None)
data.head()

,id,nhogar,miembro,comuna,dominio,edad,sexo,parentesco_jefe,situacion_conyugal,num_miembro_padre,num_miembro_madre,estado_ocupacional,cat_ocupacional,calidad_ingresos_lab,ingreso_total_lab,calidad_ingresos_no_lab,ingreso_total_no_lab,calidad_ingresos_totales,ingresos_totales,calidad_ingresos_familiares,ingresos_familiares,ingreso_per_capita_familiar,estado_educativo,sector_educativo,nivel_actual,nivel_max_educativo,años_escolaridad,lugar_nacimiento,afiliacion_salud,hijos_nacidos_vivos,cantidad_hijos_nac_vivos
0,1,1,1,5,Resto de la Ciudad,18,Mujer,Jefe,Soltero/a,Padre no vive en el hogar,Madre no vive en el hogar,Inactivo,No corresponde,No tuvo ingresos,0,Tuvo ingresos y declara monto,6000,Tuvo ingresos y declara monto,6000,Tuvo ingresos y declara monto,18000,9000,Asiste,Estatal/publico,Universitario,Otras escuelas especiales,12,PBA excepto GBA,Solo obra social,No,No corresponde
1,1,1,2,5,Resto de la Ciudad,18,Mujer,Otro no familiar,Soltero/a,Padre no vive en el hogar,Madre no vive en el hogar,Inactivo,No corresponde,No tuvo ingresos,0,Tuvo ingresos y declara monto,12000,Tuvo ingresos y declara monto,12000,Tuvo ingresos y declara monto,18000,9000,Asiste,Estatal/publico,Universitario,Otras escuelas especiales,12,Otra provincia,Solo plan de medicina prepaga por contratación...,No,No corresponde
2,2,1,1,2,Resto de la Ciudad,18,Varon,Jefe,Soltero/a,Padre no vive en el hogar,2,Inactivo,No corresponde,No tuvo ingresos,0,No tuvo ingresos,0,No tuvo ingresos,0,Tuvo ingresos pero no declara monto,100000,33333,Asiste,Privado religioso,Universitario,Otras escuelas especiales,12,CABA,Solo plan de medicina prepaga por contratación...,NaN,No corresponde
3,2,1,2,2,Resto de la Ciudad,50,Mujer,Padre/Madre/Suegro/a,Viudo/a,No corresponde,No corresponde,Ocupado,Asalariado,Tuvo ingresos y declara monto,70000,Tuvo ingresos pero no declara monto,30000,Tuvo ingresos pero no declara monto,100000,Tuvo ingresos pero no declara monto,100000,33333,No asiste pero asistió,No corresponde,No corresponde,Secundario/medio comun,17,CABA,Solo prepaga o mutual via OS,Si,2
4,2,1,3,2,Resto de la Ciudad,17,Varon,Otro familiar,Soltero/a,Padre no vive en el hogar,2,Inactivo,No corresponde,No tuvo ingresos,0,No tuvo ingresos,0,No tuvo ingresos,0,Tuvo ingresos pero no declara monto,100000,33333,Asiste,Privado religioso,Secundario/medio comun,EGB (1° a 9° año),10,CABA,Solo plan de medicina prepaga por contratación...,NaN,No corresponde

In [184]:
##data_s=data.sample(frac=0.01)
data.columns

Index(['id', 'nhogar', 'miembro', 'comuna', 'dominio', 'edad', 'sexo',
       'parentesco_jefe', 'situacion_conyugal', 'num_miembro_padre',
       'num_miembro_madre', 'estado_ocupacional', 'cat_ocupacional',
       'calidad_ingresos_lab', 'ingreso_total_lab', 'calidad_ingresos_no_lab',
       'ingreso_total_no_lab', 'calidad_ingresos_totales', 'ingresos_totales',
       'calidad_ingresos_familiares', 'ingresos_familiares',
       'ingreso_per_capita_familiar', 'estado_educativo', 'sector_educativo',
       'nivel_actual', 'nivel_max_educativo', 'años_escolaridad',
       'lugar_nacimiento', 'afiliacion_salud', 'hijos_nacidos_vivos',
       'cantidad_hijos_nac_vivos'],
      dtype='object')

In [185]:
data = data.drop({'id','hijos_nacidos_vivos'},axis=1)

In [186]:
ingreso_f, saved_bins_f = pd.qcut(data['ingresos_familiares'],q=8,retbins=True)

In [187]:
freq_tbl(ingreso_f)
ingreso_f.value_counts()

ingresos_familiares
(54000.0, 70000.0]       1905
(30000.0, 42000.0]       1841
(20800.0, 30000.0]       1810
(-0.001, 20800.0]        1796
(124000.0, 1000000.0]    1788
(70000.0, 90000.0]       1781
(42000.0, 54000.0]       1721
(90000.0, 124000.0]      1677
Name: count, dtype: int64

In [188]:
ingreso_perc, ret_bins_perc = pd.qcut(data['ingreso_per_capita_familiar'],q=10,retbins=True)

In [189]:
ingreso_perc.value_counts()

ingreso_per_capita_familiar
(24000.0, 30000.0]      1594
(8700.0, 12000.0]       1554
(19900.0, 24000.0]      1460
(-0.001, 5400.0]        1434
(15016.0, 19900.0]      1432
(52340.0, 1000000.0]    1432
(5400.0, 8700.0]        1431
(38300.0, 52340.0]      1430
(12000.0, 15016.0]      1309
(30000.0, 38300.0]      1243
Name: count, dtype: int64

In [190]:
data['ingreso_total_lab'] = pd.qcut(data['ingreso_total_lab'], q=10, duplicates='drop')
data['ingreso_total_no_lab'] = pd.qcut(data['ingreso_total_no_lab'], q=4, duplicates='drop')
data['ingreso_total_lab'].value_counts()

ingreso_total_lab
(-0.001, 2500.0]        7168
(2500.0, 15000.0]       1499
(25000.0, 37000.0]      1431
(56000.0, 1000000.0]    1427
(15000.0, 25000.0]      1397
(37000.0, 56000.0]      1397
Name: count, dtype: int64

In [191]:
data['ingresos_familiares']=ingreso_f
data['ingreso_per_capita_familiar'] = ingreso_perc

In [192]:
data['ingresos_familiares'].value_counts()

ingresos_familiares
(54000.0, 70000.0]       1905
(30000.0, 42000.0]       1841
(20800.0, 30000.0]       1810
(-0.001, 20800.0]        1796
(124000.0, 1000000.0]    1788
(70000.0, 90000.0]       1781
(42000.0, 54000.0]       1721
(90000.0, 124000.0]      1677
Name: count, dtype: int64

In [193]:
data.head()

,nhogar,miembro,comuna,dominio,edad,sexo,parentesco_jefe,situacion_conyugal,num_miembro_padre,num_miembro_madre,estado_ocupacional,cat_ocupacional,calidad_ingresos_lab,ingreso_total_lab,calidad_ingresos_no_lab,ingreso_total_no_lab,calidad_ingresos_totales,ingresos_totales,calidad_ingresos_familiares,ingresos_familiares,ingreso_per_capita_familiar,estado_educativo,sector_educativo,nivel_actual,nivel_max_educativo,años_escolaridad,lugar_nacimiento,afiliacion_salud,cantidad_hijos_nac_vivos
0,1,1,5,Resto de la Ciudad,18,Mujer,Jefe,Soltero/a,Padre no vive en el hogar,Madre no vive en el hogar,Inactivo,No corresponde,No tuvo ingresos,"(-0.001, 2500.0]",Tuvo ingresos y declara monto,"(4000.0, 500000.0]",Tuvo ingresos y declara monto,6000,Tuvo ingresos y declara monto,"(-0.001, 20800.0]","(8700.0, 12000.0]",Asiste,Estatal/publico,Universitario,Otras escuelas especiales,12,PBA excepto GBA,Solo obra social,No corresponde
1,1,2,5,Resto de la Ciudad,18,Mujer,Otro no familiar,Soltero/a,Padre no vive en el hogar,Madre no vive en el hogar,Inactivo,No corresponde,No tuvo ingresos,"(-0.001, 2500.0]",Tuvo ingresos y declara monto,"(4000.0, 500000.0]",Tuvo ingresos y declara monto,12000,Tuvo ingresos y declara monto,"(-0.001, 20800.0]","(8700.0, 12000.0]",Asiste,Estatal/publico,Universitario,Otras escuelas especiales,12,Otra provincia,Solo plan de medicina prepaga por contratación...,No corresponde
2,1,1,2,Resto de la Ciudad,18,Varon,Jefe,Soltero/a,Padre no vive en el hogar,2,Inactivo,No corresponde,No tuvo ingresos,"(-0.001, 2500.0]",No tuvo ingresos,"(-0.001, 4000.0]",No tuvo ingresos,0,Tuvo ingresos pero no declara monto,"(90000.0, 124000.0]","(30000.0, 38300.0]",Asiste,Privado religioso,Universitario,Otras escuelas especiales,12,CABA,Solo plan de medicina prepaga por contratación...,No corresponde
3,1,2,2,Resto de la Ciudad,50,Mujer,Padre/Madre/Suegro/a,Viudo/a,No corresponde,No corresponde,Ocupado,Asalariado,Tuvo ingresos y declara monto,"(56000.0, 1000000.0]",Tuvo ingresos pero no declara monto,"(4000.0, 500000.0]",Tuvo ingresos pero no declara monto,100000,Tuvo ingresos pero no declara monto,"(90000.0, 124000.0]","(30000.0, 38300.0]",No asiste pero asistió,No corresponde,No corresponde,Secundario/medio comun,17,CABA,Solo prepaga o mutual via OS,2
4,1,3,2,Resto de la Ciudad,17,Varon,Otro familiar,Soltero/a,Padre no vive en el hogar,2,Inactivo,No corresponde,No tuvo ingresos,"(-0.001, 2500.0]",No tuvo ingresos,"(-0.001, 4000.0]",No tuvo ingresos,0,Tuvo ingresos pero no declara monto,"(90000.0, 124000.0]","(30000.0, 38300.0]",Asiste,Privado religioso,Secundario/medio comun,EGB (1° a 9° año),10,CABA,Solo plan de medicina prepaga por contratación...,No corresponde

In [194]:
data['ingreso_total_no_lab'].value_counts()

ingreso_total_no_lab
(-0.001, 4000.0]      10741
(4000.0, 500000.0]     3578
Name: count, dtype: int64

In [195]:
data['edad'] = pd.cut(data['edad'],bins=5)

In [196]:
data['edad'].value_counts()

edad
(20.0, 40.0]     4204
(-0.1, 20.0]     3669
(40.0, 60.0]     3452
(60.0, 80.0]     2448
(80.0, 100.0]     546
Name: count, dtype: int64

In [197]:
data['comuna'] = data['comuna'].apply(str)

In [198]:
data['nhogar'] = data['nhogar'].apply(str)

In [199]:
data['años_escolaridad'].unique()

array(['12', '17', '10', '8', 'Ningun año de escolaridad aprobado', '11',
       '9', '13', '7', '16', '14', '15', '5', '6', '2', '19', '4', '1',
       '3', '18', nan], dtype=object)

In [200]:
data['años_escolaridad'] = data['años_escolaridad'].replace('Ningun año de escolaridad aprobado','0')

In [201]:
data['años_escolaridad'].unique()

array(['12', '17', '10', '8', '0', '11', '9', '13', '7', '16', '14', '15',
       '5', '6', '2', '19', '4', '1', '3', '18', nan], dtype=object)

In [202]:
data['años_escolaridad'] = data['años_escolaridad'].astype(float)

In [203]:
data['años_escolaridad'] = pd.qcut(data['años_escolaridad'],q=5)

In [204]:
data['años_escolaridad'].value_counts()
freq_tbl(data['años_escolaridad'])

  años_escolaridad  frequency  percentage  cumulative_perc
0    (-0.001, 7.0]       3851    0.268943         0.270113
1     (12.0, 16.0]       3037    0.212096         0.483131
2     (11.0, 12.0]       2824    0.197220         0.681209
3     (16.0, 19.0]       2570    0.179482         0.861472
4      (7.0, 11.0]       1975    0.137929         1.000000

In [205]:
data = data.dropna(subset=['situacion_conyugal', 'sector_educativo',
       'lugar_nacimiento', 'afiliacion_salud'])

In [206]:
data = data.reset_index(drop=True)

In [207]:
data['nivel_max_educativo'].fillna('desconocido',inplace=True)

C:\Users\Mariano\AppData\Local\Temp\ipykernel_15696\142472688.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['nivel_max_educativo'].fillna('desconocido',inplace=True)

In [208]:
data['años_escolaridad'] = data['años_escolaridad'].cat.add_categories('desconocido')

In [209]:
data['años_escolaridad'].fillna('desconocido',inplace=True)

C:\Users\Mariano\AppData\Local\Temp\ipykernel_15696\769594374.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['años_escolaridad'].fillna('desconocido',inplace=True)

In [210]:
freq_tbl(data['años_escolaridad'])

  años_escolaridad  frequency  percentage  cumulative_perc
0    (-0.001, 7.0]       3848    0.268903         0.268903
1     (12.0, 16.0]       3037    0.212229         0.481132
2     (11.0, 12.0]       2822    0.197205         0.678337
3     (16.0, 19.0]       2568    0.179455         0.857792
4      (7.0, 11.0]       1973    0.137876         0.995667
5      desconocido         62    0.004333         1.000000

In [211]:
status(data)

,variable,q_nan,p_nan,q_zeros,p_zeros,unique,type
0,nhogar,0,0.0,0,0.00000,7,object
1,miembro,0,0.0,0,0.00000,19,int64
2,comuna,0,0.0,0,0.00000,15,object
3,dominio,0,0.0,0,0.00000,2,object
4,edad,0,0.0,0,0.00000,5,category
5,sexo,0,0.0,0,0.00000,2,object
6,parentesco_jefe,0,0.0,0,0.00000,9,object
7,situacion_conyugal,0,0.0,0,0.00000,7,object
8,num_miembro_padre,0,0.0,0,0.00000,9,object
9,num_miembro_madre,0,0.0,0,0.00000,11,object
10,estado_ocupacional,0,0.0,0,0.00000,3,object
11,cat_ocupacional,0,0.0,0,0.00000,5,object
12,calidad_ingresos_lab,0,0.0,0,0.00000,4,object
13,ingreso_total_lab,0,0.0,0,0.00000,6,category
14,calidad_ingresos_no_lab,0,0.0,0,0.00000,4,object
15,ingreso_total_no_lab,0,0.0,0,0.00000,2,category
16,calidad_ingresos_totales,0,0.0,0,0.00000,4,object
17,ingresos_totales,0,0.0,4290,0.29979,678,int64
18,calidad_ingresos_familiares,0,0.0,0,0.00000,3,object
19,ingresos_familiares,0,0.0,0,0.00000,8,category
20,ingreso_per_capita_familiar,0,0.0,0,0.00000,10,category
21,estado_educativo,0,0.0,0,0.00000,3,object
22,sector_educativo,0,0.0,0,0.00000,4,object
23,nivel_actual,0,0.0,0,0.00000,14,object
24,nivel_max_educativo,0,0.0,0,0.00000,8,object
25,años_escolaridad,0,0.0,0,0.00000,6,category
26,lugar_nacimiento,0,0.0,0,0.00000,7,object
27,afiliacion_salud,0,0.0,0,0.00000,5,object
28,cantidad_hijos_nac_vivos,0,0.0,0,0.00000,14,object

# Consigna 2

In [212]:
import pickle
data_ohe = pd.get_dummies(data)
with open ('categories_ohe.pickle','wb') as handle:
    pickle.dump(data_ohe.columns,handle,protocol=pickle.HIGHEST_PROTOCOL)

In [213]:
new_data = pd.read_csv('new_data.csv')

In [214]:
data_ohe.columns

Index(['miembro', 'ingresos_totales', 'nhogar_1', 'nhogar_2', 'nhogar_3',
       'nhogar_4', 'nhogar_5', 'nhogar_6', 'nhogar_7', 'comuna_1',
       ...
       'cantidad_hijos_nac_vivos_15', 'cantidad_hijos_nac_vivos_2',
       'cantidad_hijos_nac_vivos_3', 'cantidad_hijos_nac_vivos_4',
       'cantidad_hijos_nac_vivos_5', 'cantidad_hijos_nac_vivos_6',
       'cantidad_hijos_nac_vivos_7', 'cantidad_hijos_nac_vivos_8',
       'cantidad_hijos_nac_vivos_9',
       'cantidad_hijos_nac_vivos_No corresponde'],
      dtype='object', length=179)

In [222]:
with open('categories_ohe.pickle', 'rb') as handle:
    columns_ohe = pickle.load(handle)

In [224]:
new_data = pd.get_dummies(new_data).reindex(columns=columns_ohe)

In [226]:
new_data.fillna(0,inplace=True)

In [228]:
pd.set_option('display.max_rows', None)
status(new_data)

,variable,q_nan,p_nan,q_zeros,p_zeros,unique,type
0,miembro,0,0.0,0,0.0,2,int64
1,ingresos_totales,0,0.0,0,0.0,5,int64
2,nhogar_1,0,0.0,5,1.0,1,float64
3,nhogar_2,0,0.0,5,1.0,1,float64
4,nhogar_3,0,0.0,5,1.0,1,float64
5,nhogar_4,0,0.0,5,1.0,1,float64
6,nhogar_5,0,0.0,5,1.0,1,float64
7,nhogar_6,0,0.0,5,1.0,1,float64
8,nhogar_7,0,0.0,5,1.0,1,float64
9,comuna_1,0,0.0,5,1.0,1,float64
10,comuna_10,0,0.0,5,1.0,1,float64
11,comuna_11,0,0.0,5,1.0,1,float64
12,comuna_12,0,0.0,5,1.0,1,float64
13,comuna_13,0,0.0,5,1.0,1,float64
14,comuna_14,0,0.0,5,1.0,1,float64
15,comuna_15,0,0.0,5,1.0,1,float64
16,comuna_2,0,0.0,5,1.0,1,float64
17,comuna_3,0,0.0,5,1.0,1,float64
18,comuna_4,0,0.0,5,1.0,1,float64
19,comuna_5,0,0.0,5,1.0,1,float64
20,comuna_6,0,0.0,5,1.0,1,float64
21,comuna_7,0,0.0,5,1.0,1,float64
22,comuna_8,0,0.0,5,1.0,1,float64
23,comuna_9,0,0.0,5,1.0,1,float64
24,dominio_Resto de la Ciudad,0,0.0,0,0.0,1,bool
25,dominio_Villas de emergencia,0,0.0,5,1.0,1,float64
26,"edad_(-0.1, 20.0]",0,0.0,5,1.0,1,float64
27,"edad_(20.0, 40.0]",0,0.0,5,1.0,1,float64
28,"edad_(40.0, 60.0]",0,0.0,5,1.0,1,float64
29,"edad_(60.0, 80.0]",0,0.0,5,1.0,1,float64
30,"edad_(80.0, 100.0]",0,0.0,5,1.0,1,float64
31,sexo_Mujer,0,0.0,4,0.8,2,bool
32,sexo_Varon,0,0.0,1,0.2,2,bool
33,parentesco_jefe_Conyugue o pareja,0,0.0,5,1.0,1,float64
34,parentesco_jefe_Hijo/a - Hijastro/a,0,0.0,5,1.0,1,float64
35,parentesco_jefe_Jefe,0,0.0,1,0.2,2,bool
36,parentesco_jefe_Nieto/a,0,0.0,5,1.0,1,float64
37,parentesco_jefe_Otro familiar,0,0.0,4,0.8,2,bool
38,parentesco_jefe_Otro no familiar,0,0.0,5,1.0,1,float64
39,parentesco_jefe_Padre/Madre/Suegro/a,0,0.0,5,1.0,1,float64
40,parentesco_jefe_Servicio domestico y sus famil...,0,0.0,5,1.0,1,float64
41,parentesco_jefe_Yerno/nuera,0,0.0,5,1.0,1,float64
42,situacion_conyugal_Casado/a,0,0.0,5,1.0,1,float64
43,situacion_conyugal_Divorciado/a,0,0.0,5,1.0,1,float64
44,situacion_conyugal_No corresponde,0,0.0,5,1.0,1,float64
45,situacion_conyugal_Separado/a de unión o matri...,0,0.0,5,1.0,1,float64
46,situacion_conyugal_Soltero/a,0,0.0,0,0.0,1,bool
47,situacion_conyugal_Unido/a,0,0.0,5,1.0,1,float64
48,situacion_conyugal_Viudo/a,0,0.0,5,1.0,1,float64
49,num_miembro_padre_1,0,0.0,5,1.0,1,float64
50,num_miembro_padre_2,0,0.0,5,1.0,1,float64
51,num_miembro_padre_3,0,0.0,5,1.0,1,float64
52,num_miembro_padre_4,0,0.0,5,1.0,1,float64
53,num_miembro_padre_5,0,0.0,5,1.0,1,float64
54,num_miembro_padre_6,0,0.0,5,1.0,1,float64
55,num_miembro_padre_7,0,0.0,5,1.0,1,float64
56,num_miembro_padre_No corresponde,0,0.0,5,1.0,1,float64
57,num_miembro_padre_Padre no vive en el hogar,0,0.0,0,0.0,1,bool
58,num_miembro_madre_1,0,0.0,5,1.0,1,float64
59,num_miembro_madre_15,0,0.0,5,1.0,1,float64
60,num_miembro_madre_2,0,0.0,5,1.0,1,float64
61,num_miembro_madre_3,0,0.0,5,1.0,1,float64
62,num_miembro_madre_4,0,0.0,5,1.0,1,float64
63,num_miembro_madre_5,0,0.0,5,1.0,1,float64
64,num_miembro_madre_6,0,0.0,5,1.0,1,float64
65,num_miembro_madre_7,0,0.0,5,1.0,1,float64
66,num_miembro_madre_9,0,0.0,5,1.0,1,float64
67,num_miembro_madre_Madre no vive en el hogar,0,0.0,0,0.0,1,bool
68,num_miembro_madre_No corresponde,0,0.0,5,1.0,1,float64
69,estado_ocupacional_Desocupado,0,0.0,4,0.8,2,bool
70,estado_ocupacional_Inactivo,0,0.0,3,0.6,2,bool
71,estado_ocupacional_Ocupado,0,0.0,3,0.6,2,bool
72,cat_ocupacional_Asalariado,0,0.0,4,0.8,2,bool
73,cat_ocupacional_No corresponde,0,0.0,2,0.4,2,bool
74,cat_ocupacional_Patron/empleador,0,0.0,5,1.0,1,float64
75,cat_ocupacional_Trabajador familiar,0,0.0,5,1.0,1,float64
76,cat_ocupacional_Trabajador por cuenta propia,0,0.0,4,0.8,2,bool
77,calidad_ingresos_lab_No corresponde,0,0.0,5,1.0,1,float64
78,calidad_ingresos_lab_No tuvo ingresos,0,0.0,2,0.4,2,bool
79,calidad_ingresos_lab_Tuvo ingresos pero no dec...,0,0.0,4,0.8,2,bool
80,calidad_ingresos_lab_Tuvo ingresos y declara m...,0,0.0,4,0.8,2,bool
81,"ingreso_total_lab_(-0.001, 2500.0]",0,0.0,5,1.0,1,float64
82,"ingreso_total_lab_(2500.0, 15000.0]",0,0.0,5,1.0,1,float64
83,"ingreso_total_lab_(15000.0, 25000.0]",0,0.0,5,1.0,1,float64
84,"ingreso_total_lab_(25000.0, 37000.0]",0,0.0,5,1.0,1,float64
85,"ingreso_total_lab_(37000.0, 56000.0]",0,0.0,5,1.0,1,float64
86,"ingreso_total_lab_(56000.0, 1000000.0]",0,0.0,5,1.0,1,float64
87,calidad_ingresos_no_lab_No corresponde,0,0.0,5,1.0,1,float64
88,calidad_ingresos_no_lab_No tuvo ingresos,0,0.0,4,0.8,2,bool
89,calidad_ingresos_no_lab_Tuvo ingresos pero no ...,0,0.0,5,1.0,1,float64
90,calidad_ingresos_no_lab_Tuvo ingresos y declar...,0,0.0,1,0.2,2,bool
91,"ingreso_total_no_lab_(-0.001, 4000.0]",0,0.0,5,1.0,1,float64
92,"ingreso_total_no_lab_(4000.0, 500000.0]",0,0.0,5,1.0,1,float64
93,calidad_ingresos_totales_No corresponde,0,0.0,5,1.0,1,float64
94,calidad_ingresos_totales_No tuvo ingresos,0,0.0,5,1.0,1,float64
95,calidad_ingresos_totales_Tuvo ingresos pero no...,0,0.0,4,0.8,2,bool
96,calidad_ingresos_totales_Tuvo ingresos y decla...,0,0.0,1,0.2,2,bool
97,calidad_ingresos_familiares_No tuvo ingresos,0,0.0,5,1.0,1,float64
98,calidad_ingresos_familiares_Tuvo ingresos pero...,0,0.0,3,0.6,2,bool
99,calidad_ingresos_familiares_Tuvo ingresos y de...,0,0.0,2,0.4,2,bool
100,"ingresos_familiares_(-0.001, 20800.0]",0,0.0,5,1.0,1,float64
101,"ingresos_familiares_(20800.0, 30000.0]",0,0.0,5,1.0,1,float64
102,"ingresos_familiares_(30000.0, 42000.0]",0,0.0,5,1.0,1,float64
103,"ingresos_familiares_(42000.0, 54000.0]",0,0.0,5,1.0,1,float64
104,"ingresos_familiares_(54000.0, 70000.0]",0,0.0,5,1.0,1,float64
105,"ingresos_familiares_(70000.0, 90000.0]",0,0.0,5,1.0,1,float64
106,"ingresos_familiares_(90000.0, 124000.0]",0,0.0,5,1.0,1,float64
107,"ingresos_familiares_(124000.0, 1000000.0]",0,0.0,5,1.0,1,float64
108,"ingreso_per_capita_familiar_(-0.001, 5400.0]",0,0.0,5,1.0,1,float64
109,"ingreso_per_capita_familiar_(5400.0, 8700.0]",0,0.0,5,1.0,1,float64
110,"ingreso_per_capita_familiar_(8700.0, 12000.0]",0,0.0,5,1.0,1,float64
111,"ingreso_per_capita_familiar_(12000.0, 15016.0]",0,0.0,5,1.0,1,float64
112,"ingreso_per_capita_familiar_(15016.0, 19900.0]",0,0.0,5,1.0,1,float64
113,"ingreso_per_capita_familiar_(19900.0, 24000.0]",0,0.0,5,1.0,1,float64
114,"ingreso_per_capita_familiar_(24000.0, 30000.0]",0,0.0,5,1.0,1,float64
115,"ingreso_per_capita_familiar_(30000.0, 38300.0]",0,0.0,5,1.0,1,float64
116,"ingreso_per_capita_familiar_(38300.0, 52340.0]",0,0.0,5,1.0,1,float64
117,"ingreso_per_capita_familiar_(52340.0, 1000000.0]",0,0.0,5,1.0,1,float64
118,estado_educativo_Asiste,0,0.0,0,0.0,1,bool
119,estado_educativo_No asiste pero asistió,0,0.0,5,1.0,1,float64
120,estado_educativo_Nunca asistio,0,0.0,5,1.0,1,float64
121,sector_educativo_Estatal/publico,0,0.0,4,0.8,2,bool
122,sector_educativo_No corresponde,0,0.0,5,1.0,1,float64
123,sector_educativo_Privado no religioso,0,0.0,2,0.4,2,bool
124,sector_educativo_Privado religioso,0,0.0,4,0.8,2,bool
125,nivel_actual_Jardin maternal,0,0.0,5,1.0,1,float64
126,nivel_actual_No corresponde,0,0.0,5,1.0,1,float64
127,nivel_actual_Otras escuelas especiales,0,0.0,5,1.0,1,float64
128,nivel_actual_Postgrado,0,0.0,5,1.0,1,float64
129,nivel_actual_Primario adultos,0,0.0,5,1.0,1,float64
130,nivel_actual_Primario comun,0,0.0,5,1.0,1,float64
131,nivel_actual_Primario especial,0,0.0,5,1.0,1,float64
132,nivel_actual_Sala de 3,0,0.0,5,1.0,1,float64
133,nivel_actual_Sala de 4,0,0.0,5,1.0,1,float64
134,nivel_actual_Sala de 5,0,0.0,5,1.0,1,float64
135,nivel_actual_Secundario/medio adultos,0,0.0,5,1.0,1,float64
136,nivel_actual_Secundario/medio comun,0,0.0,5,1.0,1,float64
137,nivel_actual_Terciario/superior no universitario,0,0.0,5,1.0,1,float64
138,nivel_actual_Universitario,0,0.0,0,0.0,1,bool
139,nivel_max_educativo_EGB (1° a 9° año),0,0.0,5,1.0,1,float64
140,nivel_max_educativo_No corresponde,0,0.0,5,1.0,1,float64
141,nivel_max_educativo_Otras escuelas especiales,0,0.0,0,0.0,1,bool
142,nivel_max_educativo_Primario comun,0,0.0,5,1.0,1,float64
143,nivel_max_educativo_Primario especial,0,0.0,5,1.0,1,float64
144,nivel_max_educativo_Sala de 5,0,0.0,5,1.0,1,float64
145,nivel_max_educativo_Secundario/medio comun,0,0.0,5,1.0,1,float64
146,nivel_max_educativo_desconocido,0,0.0,5,1.0,1,float64
147,"años_escolaridad_(-0.001, 7.0]",0,0.0,5,1.0,1,float64
148,"años_escolaridad_(7.0, 11.0]",0,0.0,5,1.0,1,float64
149,"años_escolaridad_(11.0, 12.0]",0,0.0,5,1.0,1,float64
150,"años_escolaridad_(12.0, 16.0]",0,0.0,5,1.0,1,float64
151,"años_escolaridad_(16.0, 19.0]",0,0.0,5,1.0,1,float64
152,años_escolaridad_desconocido,0,0.0,5,1.0,1,float64
153,lugar_nacimiento_CABA,0,0.0,3,0.6,2,bool
154,lugar_nacimiento_Otra provincia,0,0.0,3,0.6,2,bool
155,lugar_nacimiento_PBA excepto GBA,0,0.0,4,0.8,2,bool
156,lugar_nacimiento_PBA sin especificar,0,0.0,5,1.0,1,float64
157,lugar_nacimiento_Pais limitrofe,0,0.0,5,1.0,1,float64
158,lugar_nacimiento_Pais no limitrofe,0,0.0,5,1.0,1,float64
159,lugar_nacimiento_Partido GBA,0,0.0,5,1.0,1,float64
160,afiliacion_salud_Otros,0,0.0,4,0.8,2,bool
161,afiliacion_salud_Solo obra social,0,0.0,4,0.8,2,bool
162,afiliacion_salud_Solo plan de medicina prepaga...,0,0.0,2,0.4,2,bool
163,afiliacion_salud_Solo prepaga o mutual via OS,0,0.0,5,1.0,1,float64
164,afiliacion_salud_Solo sistema publico,0,0.0,5,1.0,1,float64
165,cantidad_hijos_nac_vivos_1,0,0.0,5,1.0,1,float64
166,cantidad_hijos_nac_vivos_10,0,0.0,5,1.0,1,float64
167,cantidad_hijos_nac_vivos_11,0,0.0,5,1.0,1,float64
168,cantidad_hijos_nac_vivos_12,0,0.0,5,1.0,1,float64
169,cantidad_hijos_nac_vivos_15,0,0.0,5,1.0,1,float64
170,cantidad_hijos_nac_vivos_2,0,0.0,5,1.0,1,float64
171,cantidad_hijos_nac_vivos_3,0,0.0,5,1.0,1,float64
172,cantidad_hijos_nac_vivos_4,0,0.0,5,1.0,1,float64
173,cantidad_hijos_nac_vivos_5,0,0.0,5,1.0,1,float64
174,cantidad_hijos_nac_vivos_6,0,0.0,5,1.0,1,float64
175,cantidad_hijos_nac_vivos_7,0,0.0,5,1.0,1,float64
176,cantidad_hijos_nac_vivos_8,0,0.0,5,1.0,1,float64
177,cantidad_hijos_nac_vivos_9,0,0.0,5,1.0,1,float64
178,cantidad_hijos_nac_vivos_No corresponde,0,0.0,0,0.0,1,bool

# Dudas

### No comprendo lo de los duplicados
data['ingreso_total_lab'] = pd.qcut(data['ingreso_total_lab'], q=10, duplicates='drop')

data['ingreso_total_no_lab'] = pd.qcut(data['ingreso_total_no_lab'], q=4, duplicates='drop')


### Como hago para modificar varias columnas en simultaneo??

data2[['comuna','nhogar']] = [[data2['comuna'].apply(str)],[data2['nhogar'].apply(str)]]

### No me permite pasar de float a int si hay algún nan
data['años_escolaridad'] = data['años_escolaridad'].astype(float).astype('int32')